services:
  scvue:
    build: ./vue
    ports:
      - "8080:80"
    depends_on:
      - scwp
  scwp:
    build: ./wp
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wp/themes:/var/www/html/wp-content/themes
      - ./wp/plugins:/var/www/html/wp-content/plugins
    ports:
      - "8081:80"