services:
  scvue:
    build: ./vue
    ports:
      - "8083:80"
    depends_on:
      - scwp
  scwp:
    build: ./wp
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wp/themes:/var/www/html/wp-content/themes
      - ./wp/plugins:/var/www/html/wp-content/plugins
    ports:
      - "8082:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: always